### ISSUE TITLE
brew install wsmoses/tools/cilkrts is failing

### ISSUE THREAD

**Issue by juraev** [wsmoses/homebrew-tools#3]
Hi, I am getting ChecksumMismatchError.

$ brew install wsmoses/tools/cilkrts
==> Installing cilkrts from wsmoses/tools
==> Downloading http://cilk.mit.edu/cilkrts.tgz
######################################################################## 100.0%
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: d4341b0ae9c955cc680d41d5ac2fd02131169726d8aa9fee6ce2368811a79b9c
  Actual: 7b2ff7b57e621567765fb6a9dada820f7fffff99a5958ae286bd1c7ac37ac732
 Archive: /Users/user/Library/Caches/Homebrew/downloads/9f47f9e4adf0dc9f96254d3ffab95b21fcb06ba5a36d87dfa94fc65c1135b9db--cilkrts.tgz
To retry an incomplete download, remove the file above.

**Comment by wsmoses** [comment]
Resolved in b8f71a00230e4f00d6ec508824bc9ef2d48efbd9
